# Generated by Django 3.0.3 on 2020-03-04 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_demand_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demand',
            old_name='items',
            new_name='f_content',
        ),
    ]
