# Generated by Django 3.0.3 on 2020-03-04 18:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200304_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='supp_content',
            field=models.FileField(default=django.utils.timezone.now, upload_to='supported_content/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demand',
            name='f_content',
            field=models.FileField(upload_to='fullfilled_content/'),
        ),
    ]
