# Generated by Django 3.0.3 on 2020-03-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200304_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='supp_content',
            field=models.FileField(upload_to='supporting_content/'),
        ),
    ]
