# Generated by Django 3.0.3 on 2020-03-04 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200304_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='f_suggestion',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
