# Generated by Django 3.0.3 on 2020-03-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_demand_f_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='fulfiller',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='f_suggestion',
            field=models.CharField(max_length=500),
        ),
    ]
