# Generated by Django 3.0.3 on 2020-03-04 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_demand_uploaded_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demand',
            old_name='fulfiller',
            new_name='d_fulfiller',
        ),
    ]
