# Generated by Django 3.0.3 on 2020-03-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20200304_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
