# Generated by Django 3.0.3 on 2020-03-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_demand_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
