# Generated by Django 3.0.3 on 2020-03-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_demand_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
