# Generated by Django 3.0.3 on 2020-03-20 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0014_auto_20200304_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandFulfiller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Demand')),
                ('fulfiller_id', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
