# Generated by Django 3.0.3 on 2020-03-20 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_demandfulfiller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandfulfiller',
            old_name='demand_id',
            new_name='demand',
        ),
        migrations.RenameField(
            model_name='demandfulfiller',
            old_name='fulfiller_id',
            new_name='fulfiller',
        ),
    ]
