# Generated by Django 3.0.3 on 2020-03-21 12:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0016_auto_20200320_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='d_fulfiller',
        ),
        migrations.AddField(
            model_name='demand',
            name='fulfiller',
            field=models.ManyToManyField(related_name='fulfiller', to=settings.AUTH_USER_MODEL),
        ),
    ]
