# Generated by Django 3.0.3 on 2020-03-21 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0017_auto_20200321_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfillContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_suggestion', models.CharField(max_length=500)),
                ('f_content', models.FileField(upload_to='fullfilled_content/')),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Demand')),
                ('fulfiller', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
