# Generated by Django 3.0.3 on 2020-03-21 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0018_fulfillcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulfillcontent',
            name='demand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Demand'),
        ),
        migrations.RemoveField(
            model_name='fulfillcontent',
            name='fulfiller',
        ),
        migrations.AddField(
            model_name='fulfillcontent',
            name='fulfiller',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
