# Generated by Django 3.0.3 on 2020-03-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20200321_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='f_content',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='f_suggestion',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='fulfiller',
        ),
        migrations.DeleteModel(
            name='DemandFulfiller',
        ),
    ]
