# Generated by Django 3.0.3 on 2020-03-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_fulfillcontent_date_fulfilled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulfillcontent',
            name='f_content',
            field=models.FileField(null=True, upload_to='fullfilled_content/'),
        ),
        migrations.AlterField(
            model_name='fulfillcontent',
            name='f_suggestion',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
