# Generated by Django 3.0.3 on 2020-03-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20200321_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulfillcontent',
            name='f_suggestion',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
