# Generated by Django 3.0.3 on 2020-03-22 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0024_auto_20200321_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='votes',
        ),
        migrations.AddField(
            model_name='demand',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='demand_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
