# Generated by Django 3.0.3 on 2020-03-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_auto_20200322_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
