# Generated by Django 3.0.3 on 2020-03-24 13:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0027_fulfillcontent_user_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fulfillcontent',
            name='user_likes',
        ),
        migrations.AddField(
            model_name='fulfillcontent',
            name='user_votes',
            field=models.ManyToManyField(blank=True, related_name='user_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
